spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration/dev
    baseline-on-migrate: true
    baseline-version: 1
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_SECRET}
            redirect-uri: http://ec2-3-37-207-190.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
            client-name: Naver

          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: http://ec2-3-37-207-190.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  data:
    redis:
      host: ${AWS_REDIS_HOST}
      port: ${AWS_REDIS_PORT}

    mongodb:
      uri: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@3.37.207.190:27017/
#      host: localhost
#      port: 27017
#      authentication-database: admin
#      username: ${DATABASE_USERNAME}
#      password: ${DATABASE_PASSWORD}

jwt:
  secretKey: ${JWT_SECRET_KEY}

  access:
    expiration: 3600000 #1시간
    header: Authorization

  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hibernate:
        SQL: debug
