spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
    username: climb
    password: climb

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  profiles:
    active: local
    include:
      - jwt
      - oauth
  thymeleaf:
    prefix: /templates/
    suffix: .html

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hibernate:
        SQL: debug

