version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: root
    group: root
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 120
      runas: root
